<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<RootNamespace>NSail.Components</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<SupportedStack Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
		<PackageReference Include="MudBlazor" Version="9.10.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NSail.Components\NSail.Components.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="NSail.Components.Tests" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="strings*.json" />
		<EmbeddedResource Update="strings.*.json">
			<DependentUpon>strings.json</DependentUpon>
			<LogicalName>$(RootNamespace).%(Filename)%(Extension)</LogicalName>
			<WithCulture>false</WithCulture>
		</EmbeddedResource>
	</ItemGroup>

</Project>
