// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Leonardo Porro and Emmanuel Arias. https://github.com/nsail-ar/nsail-stack

using System.Text;
using System.Text.Json;

namespace NSail.TypeScriptGenerator;

// Every exported name is declared twice on purpose — a type and a value of the same name, which
// TypeScript keeps in separate spaces: the interface is what a caller writes, the descriptor is
// what the runtime reads (route, binding, rules, keys), so a send reads like the C# one —
// mediator.send(CreateContact, { ... }).
static class TypeScriptWriter
{
    public static string Write(SdkModel model)
    {
        var text = new StringBuilder();

        text.AppendLine("// <auto-generated>");
        text.AppendLine($"// NSail.TypeScriptGenerator, from {string.Join(", ", model.Sources)}.");
        text.AppendLine("// Written on every build of the host: an edit here is lost; change the Sdk instead.");
        text.AppendLine("// </auto-generated>");
        text.AppendLine("/* eslint-disable */");
        text.AppendLine("import { defineEnum, defineMessage, defineModel } from \"@nsail/stack\";");

        foreach (var shape in model.Enums)
        {
            WriteEnum(text, shape);
        }

        foreach (var shape in model.Models)
        {
            WriteModel(text, shape);
        }

        foreach (var shape in model.Messages)
        {
            WriteMessage(text, shape);
        }

        return text.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    static void WriteEnum(StringBuilder text, EnumShape shape)
    {
        var values = string.Join(", ", shape.Values.Select(Quote));

        text.AppendLine();
        text.AppendLine($"export type {shape.Name} = {string.Join(" | ", shape.Values.Select(Quote))};");
        text.AppendLine($"export const {shape.Name} = defineEnum<{shape.Name}>({Quote(shape.Key)}, [{values}]);");
    }

    static void WriteModel(StringBuilder text, ModelShape shape)
    {
        var parameters = shape.TypeParameters.Count == 0 ? string.Empty : $"<{string.Join(", ", shape.TypeParameters)}>";

        text.AppendLine();
        text.AppendLine($"export interface {shape.Name}{parameters} {{");

        foreach (var field in shape.Fields)
        {
            text.AppendLine($"  {field.Name}: {field.Type.Full};");
        }

        text.AppendLine("}");

        if (shape.Key is null)
        {
            return;
        }

        text.AppendLine($"export const {shape.Name} = defineModel<{shape.Name}>({Quote(shape.Key)}, {{");

        foreach (var field in shape.Fields)
        {
            text.AppendLine($"  {field.Name}: {Descriptor(field)},");
        }

        text.AppendLine("});");
    }

    static void WriteMessage(StringBuilder text, MessageShape shape)
    {
        text.AppendLine();
        text.AppendLine($"export interface {shape.Name} {{");

        foreach (var field in shape.Fields)
        {
            text.AppendLine($"  {field.Name}{(field.Optional ? "?" : string.Empty)}: {field.Type.Full};");
        }

        text.AppendLine("}");
        text.AppendLine($"export const {shape.Name} = defineMessage<{shape.Name}, {shape.Result}>({{");
        text.AppendLine($"  name: {Quote(shape.Name)},");
        text.AppendLine($"  key: {Quote(shape.Key)},");
        text.AppendLine($"  area: {(shape.Area is null ? "null" : Quote(shape.Area))},");
        text.AppendLine($"  method: {Quote(shape.Method)},");
        text.AppendLine($"  path: {Quote(shape.Path)},");
        text.AppendLine("  fields: {");

        foreach (var field in shape.Fields)
        {
            text.AppendLine($"    {field.Name}: {Descriptor(field)},");
        }

        text.AppendLine("  },");
        text.AppendLine("});");
    }

    static string Descriptor(FieldShape field)
    {
        var parts = new List<string>
        {
            $"kind: {Quote(field.Type.Kind)}",
            $"key: {Quote(field.Key)}",
        };

        if (field.Type.Nullable)
        {
            parts.Add("nullable: true");
        }

        if (field.Type.Enum is { } enumeration)
        {
            parts.Add($"enum: {enumeration}");
        }

        if (field.Type.Element is { } element)
        {
            parts.Add($"element: {Quote(element.Kind)}");
        }

        if (field.Binding is { } binding)
        {
            parts.Add($"binding: {Quote(binding)}");
        }

        if (field.Required)
        {
            parts.Add("required: true");
        }

        if (field.MaxLength is { } maxLength)
        {
            parts.Add($"maxLength: {maxLength}");
        }

        if (field.MinLength is { } minLength)
        {
            parts.Add($"minLength: {minLength}");
        }

        if (field.Min is { } min)
        {
            parts.Add($"min: {min}");
        }

        if (field.Max is { } max)
        {
            parts.Add($"max: {max}");
        }

        if (field.Format is { } format)
        {
            parts.Add($"format: {Quote(format)}");
        }

        if (field.Pattern is { } pattern)
        {
            parts.Add($"pattern: {Quote(pattern)}");
        }

        if (field.ServerRules.Count > 0)
        {
            parts.Add($"serverRules: [{string.Join(", ", field.ServerRules.Select(Quote))}]");
        }

        return $"{{ {string.Join(", ", parts)} }}";
    }

    static string Quote(string value)
    {
        return JsonSerializer.Serialize(value);
    }
}
