<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.10" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\Stack\Generation\NSail.SourceGeneration.Annotations\NSail.SourceGeneration.Annotations.csproj" />
        <ProjectReference Include="..\..\..\..\src\Stack\Messaging\NSail.Messaging.Annotations\NSail.Messaging.Annotations.csproj" />
        <ProjectReference Include="..\..\..\..\src\Stack\Messaging\NSail.Messaging.Http\NSail.Messaging.Http.csproj" />
        <ProjectReference Include="..\..\..\..\src\Stack\Messaging\NSail.Messaging.WebApi\NSail.Messaging.WebApi.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\Stack\Generation\NSail.SourceGenerator\NSail.SourceGenerator.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <PrivateAssets>all</PrivateAssets>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
