<#
.SYNOPSIS
    Mirrors the Stack out of the nsail monorepo into this repository.

.DESCRIPTION
    Until the cutover the monorepo is the source of truth: every Stack change lands there,
    and this repository receives it through this script, one way only. Nobody edits a
    mirrored path here — the next sync overwrites it.

    The mirror is taken from a committed ref (origin/main by default), never from the
    monorepo's working tree, so a sync is reproducible from the sha it names.

    The layout is kept verbatim (src/Stack, test/Stack): the Stack's own tests find their
    files by repo-relative path, so a copy that moved folders would also have to rewrite
    code. Flattening happens once, at the cutover, when this repository becomes the source.

    What this repository owns, and the sync never touches: README.md, LICENSE, .gitignore,
    .github/, tools/, and the nested src/ and test/ Directory.Build.props/.targets (packaging
    metadata layered over the mirrored root ones). NSail.sln is
    regenerated from the monorepo's own solution, filtered to the Stack.

.PARAMETER Source
    The nsail checkout. Defaults to the sibling folder ../nsail.

.PARAMETER Ref
    The monorepo ref to mirror. Defaults to origin/main, fetched first.

.PARAMETER Commit
    Commit the result as "Sync from nsail@<sha>".
#>
param(
    [string]$Source = (Join-Path $PSScriptRoot '..\..\nsail'),
    [string]$Ref = 'origin/main',
    [switch]$Commit
)

$ErrorActionPreference = 'Stop'

$Target = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$Source = (Resolve-Path $Source).Path

# Folders mirrored whole, and single files mirrored beside them. test/Shared holds kit-named
# fixtures that stay in the monorepo; only what the Stack's tests compile comes over.
$MirroredFolders = @('src/Stack', 'test/Stack')
$MirroredFiles = @(
    'test/Shared/BunitWaitTimeout.cs',
    'test/Shared/Background/Meters.cs',
    'Directory.Build.props',
    'Directory.Build.targets',
    'global.json',
    '.editorconfig',
    '.gitattributes',
    'tsconfig.base.json',
    'package.json',
    'package-lock.json'
)

$Header = @(
    'SPDX-License-Identifier: MIT',
    'Copyright (c) 2026 Leonardo Porro and Emmanuel Arias. https://github.com/nsail-ar/nsail-stack'
)

function Invoke-Git {
    $output = & git @args
    if ($LASTEXITCODE -ne 0) { throw "git $args failed ($LASTEXITCODE)" }
    $output
}

if ($Ref -like 'origin/*') {
    Invoke-Git -C $Source fetch --quiet origin
}

$sha = (Invoke-Git -C $Source rev-parse $Ref).Trim()
Write-Host "Mirroring nsail@$sha"

# Extract the committed tree into a scratch folder. git archive writes a file rather than a
# pipe: Windows PowerShell re-encodes binary pipes and corrupts the tar. autocrlf is forced off
# so the mirror holds the blobs as committed: a machine's CRLF conversion would otherwise turn
# the newlines inside test string literals into \r\n and fail tests that pass on Linux CI.
$scratch = Join-Path ([IO.Path]::GetTempPath()) "nsail-stack-sync-$sha"
if (Test-Path $scratch) { Remove-Item $scratch -Recurse -Force }
New-Item -ItemType Directory $scratch | Out-Null
$tar = Join-Path $scratch 'tree.tar'

Invoke-Git -C $Source -c core.autocrlf=false archive --format=tar -o $tar $sha -- @($MirroredFolders + $MirroredFiles + 'NSail.sln') | Out-Null
& tar -xf $tar -C $scratch
if ($LASTEXITCODE -ne 0) { throw "tar failed ($LASTEXITCODE)" }
Remove-Item $tar

# Mirror: what the monorepo deleted disappears here too.
foreach ($folder in $MirroredFolders) {
    $destination = Join-Path $Target $folder
    if (Test-Path $destination) { Remove-Item $destination -Recurse -Force }
    Copy-Item (Join-Path $scratch $folder) $destination -Recurse
}

foreach ($file in $MirroredFiles) {
    $destination = Join-Path $Target $file
    New-Item -ItemType Directory (Split-Path $destination) -Force | Out-Null
    Copy-Item (Join-Path $scratch $file) $destination -Force
}

# License header on every source file that came over. Idempotent, keeps the file's BOM and
# line endings, and leaves generated files alone.
$utf8 = New-Object System.Text.UTF8Encoding($false)
$headed = 0

$sources = foreach ($root in ($MirroredFolders + 'test/Shared')) {
    Get-ChildItem (Join-Path $Target $root) -Recurse -File -Include *.cs, *.razor, *.ts, *.tsx
}

foreach ($file in $sources) {
    $bytes = [IO.File]::ReadAllBytes($file.FullName)
    $bom = $bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF
    $text = $utf8.GetString($bytes, $(if ($bom) { 3 } else { 0 }), $bytes.Length - $(if ($bom) { 3 } else { 0 }))

    if ($text.StartsWith("// $($Header[0])") -or $text.StartsWith("@* $($Header[0])")) { continue }

    $head = ($text -split "`n", 4 | Select-Object -First 3) -join "`n"
    if ($head -match '<auto-generated') { continue }

    $eol = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }

    $block = if ($file.Extension -eq '.razor') {
        "@* $($Header[0])$eol   $($Header[1]) *@$eol$eol"
    }
    else {
        (($Header | ForEach-Object { "// $_" }) -join $eol) + $eol + $eol
    }

    $content = $utf8.GetBytes($block + $text)
    if ($bom) { $content = [byte[]](0xEF, 0xBB, 0xBF) + $content }
    [IO.File]::WriteAllBytes($file.FullName, $content)
    $headed++
}

Write-Host "Headers added: $headed"

# The solution: the monorepo's own project list, filtered to what was mirrored. Reading its
# NSail.sln rather than the disk keeps a project that is on disk on purpose but in no solution
# (NSail.Structure) out of here too.
$projects = Select-String -Path (Join-Path $scratch 'NSail.sln') -Pattern '^Project\("\{[^}]+\}"\) = "[^"]+", "([^"]+\.csproj)"' |
    ForEach-Object { $_.Matches[0].Groups[1].Value.Replace('\', '/') } |
    Where-Object { $path = $_; $MirroredFolders | Where-Object { $path.StartsWith("$_/") } } |
    Sort-Object

# Regenerated only when the project list changed: dotnet sln add mints fresh GUIDs every time,
# and a sync that rewrites the whole solution for nothing buries the real diff.
$solution = Join-Path $Target 'NSail.sln'
$current = if (Test-Path $solution) {
    Select-String -Path $solution -Pattern '^Project\("\{[^}]+\}"\) = "[^"]+", "([^"]+\.csproj)"' |
        ForEach-Object { $_.Matches[0].Groups[1].Value.Replace('\', '/') } |
        Sort-Object
}

if (($current -join "`n") -ne ($projects -join "`n")) {
    Push-Location $Target
    try {
        & dotnet new sln --name NSail --format sln --force | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "dotnet new sln failed ($LASTEXITCODE)" }

        & dotnet sln NSail.sln add @projects | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "dotnet sln add failed ($LASTEXITCODE)" }
    }
    finally {
        Pop-Location
    }

    Write-Host "Solution regenerated: $($projects.Count) projects"
}
else {
    Write-Host "Solution unchanged: $($projects.Count) projects"
}

Remove-Item $scratch -Recurse -Force

if ($Commit) {
    $paths = $MirroredFolders + $MirroredFiles + 'NSail.sln'
    Invoke-Git -C $Target add -- @paths | Out-Null
    Invoke-Git -C $Target commit --quiet -m "Sync from nsail@$sha" | Out-Null
    Write-Host "Committed: Sync from nsail@$sha"
}
